### ISSUE TITLE
generate token option for download with CDSE

### ISSUE THREAD

**Issue by giustiandrea91** [AIRCentre/POS2IDON#12]
- when setting False in generate token option for download with CDSE, cause the next run to throw error 401. To tackle this is necessary to open the .env file, delete the token code and the refresh token code and run again the main workflow.

example:
roi={"type":"Polygon","coordinates":[[[-28.401489,38.130031],[-28.401489,38.484415],[-27.982635,38.484415],[-27.982635,38.130031],[-28.401489,38.130031]]]}
sensing_period = ('20220507', '20220509')

**Comment by EmanuelCastanho** [comment]
@giustiandrea91 test with the new version. If it works, close this issue
