### ISSUE TITLE
ACOLITE can not open auxiliar HDF file

### ISSUE THREAD

**Issue by EmanuelCastanho** [AIRCentre/POS2IDON#4]
Error example:
<img width="1121" alt="Screenshot 2023-02-22 at 11 18 10" src="https://user-images.githubusercontent.com/69935277/220623529-d631dcbc-e785-4f7f-b933-f8c812c029a6.png">

The download was not successful.

**Possible solution:** The file may be corrupted and must be replaced.

**Comment by EmanuelCastanho** [comment]
Solved.

**Comment by giustiandrea91** [comment]
The use of ancillary and SRTM DEM data requires the set up of an EarthData account (https://earthdata.nasa.gov).
Your EarthData account needs to have approval for the OB.DAAC Data Access and LP DAAC Data Pool respectively
to access these datasets.
