### ISSUE TITLE
[Errno 13] Permission denied 

### ISSUE THREAD

**Issue by giustiandrea91** [AIRCentre/POS2IDON#6]
If return the following error : ( [Errno 13] Permission denied ) 'C:\Users\--\AppData\Local\Temp\tmpcoaoqmxd'

Open fels/sentinel2.py and modify the function **get_sentinel2_image** (line 176) copying:

        if reject_old:
            # check contents of manifest before downloading the rest
            content = urlopen(manifest_url)
            #with NamedTemporaryFile() as f:
            f = NamedTemporaryFile(delete = False)
            shutil.copyfileobj(content, f)
            if not is_new(f.name):
                return False
            f.close()
            os.unlink(f.name)

**Comment by EmanuelCastanho** [comment]
Modification added to README link and function inside PreStart. Uses a fork repository
