### ISSUE TITLE
ESA world cover download incomplete 

### ISSUE THREAD

**Issue by giustiandrea91** [AIRCentre/POS2IDON#8]
when using large ROI like:
{"type":"Polygon","coordinates":[[[0.886231,50.864896],[0.886231,53.398645],[5.039063,53.398645],[5.039063,50.864896],[0.886231,50.864896]]]}

not all necessary  LC tiles are downloaded.

**Comment by EmanuelCastanho** [comment]
This is a really large region. I suggest developing an option to create a mask based on shapefile.
